### PR TITLE
fix: avoid flicker when loading login page

### PR DESCRIPTION
**Pull request by mas-who**
## Done
- Fix issue with ui showing cluster list before login page on first load.

### CODE REVIEW

**Comment by edlerd** [comment]
This doesn't solve the problem yet. See below video. I think we should render a blank page as the loader jumps around while CSS is loading on the initial land.

[Screencast from 24.07.2024 10:42:15.webm](https://github.com/user-attachments/assets/f91c02e4-b236-496a-bf34-8c11d7f4aa09)

**Comment by mas-who** [comment]
> This doesn't solve the problem yet. See below video. I think we should render a blank page as the loader jumps around while CSS is loading on the initial land.
> 
>  Screencast.from.24.07.2024.10.42.15.webm

Yeah I see, sorry I couldn't check it on the demo server yesterday (where the request delay is long enough to see this behaviour) due to a 404 error, turns out I had to clear cookies for jenkins in my browser. Will sort it out :+1:

**Review by edlerd — COMMENTED** [review]
Thanks, this is nearly perfect now. One flicker I could find is on accessing a logged in page, when not being logged in, the no match component is briefly rendered. It also seems the no match layout is off, but that is another issue.  See video below

[Screencast from 24.07.2024 13:28:09.webm](https://github.com/user-attachments/assets/0a26f2c6-230d-4226-8c55-42a3c30d9c21)

**Review by edlerd — APPROVED** [review]
Now it is perfect. Thanks :)

**Pull request merged**
